# Generated by Django 3.2.18 on 2023-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='family',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
