# Generated by Django 3.2.18 on 2023-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230516_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='relative_choices',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Son'), ('D', 'daughter')], max_length=1, null=True),
        ),
    ]
