# Generated by Django 3.2.18 on 2023-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
