# Generated by Django 3.2.18 on 2023-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_family_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
