# Generated by Django 3.2.18 on 2023-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230612_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
