# Generated by Django 3.2.18 on 2023-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_family_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
