# Generated by Django 3.2.18 on 2023-06-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_family_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
    ]
