# Generated by Django 3.2.18 on 2023-06-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_family_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='details',
            new_name='family',
        ),
    ]
